// <auto-generated />
using System;
using DevLoggerBackend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevLoggerBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevLoggerBackend.Domain.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitLink")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Learnings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("ProblemsFaced")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Solutions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TasksWorked")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tips")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LogDate");

                    b.HasIndex("UserId");

                    b.ToTable("DailyLogs", (string)null);
                });

            modelBuilder.Entity("DevLoggerBackend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d2b489f-c8f9-4f36-98fd-4a1e0e9fdd11"),
                            CreatedAtUtc = new DateTime(2026, 2, 27, 17, 5, 34, 840, DateTimeKind.Utc).AddTicks(5207),
                            Email = "john@example.com",
                            Name = "John Doe",
                            PasswordHash = "$2a$11$gHj0CTIF6KI2Rvl4hqzw1uBaTw9YAkfQourqTmM9kerpKOFI1c.Fe",
                            Role = 1,
                            UpdatedAtUtc = new DateTime(2026, 2, 27, 17, 5, 34, 840, DateTimeKind.Utc).AddTicks(5207)
                        },
                        new
                        {
                            Id = new Guid("8ac15b3b-230c-43ad-8bc4-fcb1af7f1459"),
                            CreatedAtUtc = new DateTime(2026, 2, 27, 17, 5, 34, 840, DateTimeKind.Utc).AddTicks(5207),
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            PasswordHash = "$2a$11$SuL1XY1j2PPACdaQClHZ2ejJjRIHvew5ALae.U4dLGuoO04fOOI66",
                            Role = 2,
                            UpdatedAtUtc = new DateTime(2026, 2, 27, 17, 5, 34, 840, DateTimeKind.Utc).AddTicks(5207)
                        },
                        new
                        {
                            Id = new Guid("6cf97b16-a4b9-448f-8887-f6c8a21a58ec"),
                            CreatedAtUtc = new DateTime(2026, 2, 27, 17, 5, 34, 840, DateTimeKind.Utc).AddTicks(5207),
                            Email = "bob@example.com",
                            Name = "Bob Lee",
                            PasswordHash = "$2a$11$aHO3NhtzdhgfgbONK3xn7uNQj0B3MLSme.lggL8AxWn0lH2c1UdPO",
                            Role = 3,
                            UpdatedAtUtc = new DateTime(2026, 2, 27, 17, 5, 34, 840, DateTimeKind.Utc).AddTicks(5207)
                        });
                });

            modelBuilder.Entity("DevLoggerBackend.Domain.Entities.DailyLog", b =>
                {
                    b.HasOne("DevLoggerBackend.Domain.Entities.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLoggerBackend.Domain.Entities.User", b =>
                {
                    b.Navigation("DailyLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
